name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          server-password: MAVEN_PASSWORD

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package -Djacoco.execFile='${coverage.reports.dir}/actions-jacoco.exec'
        env:
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PACKAGE_READ_TOKEN }}

      - name: Upload Jacoco coverage
        uses: actions/upload-artifact@v3
        with:
          name: actions-jacoco
          path: "./target/coverage-reports/actions-jacoco.exec"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.jar
          path: target/${{ github.event.repository.name }}.jar

  sonar:
    runs-on: self-hosted

    needs: [ build ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          server-password: MAVEN_PASSWORD

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: self-hosted-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            self-hosted-${{ runner.os }}-maven-

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarqube
          restore-keys: |
            ${{ runner.os }}-sonarqube

      - name: Download actions Jacoco coverage
        uses: actions/download-artifact@v3
        with:
          name: actions-jacoco

      - name: Run Jacoco report
        run: |
          mvn -B compile
          mvn jacoco:report@coverage-report -P jacoco-ci
        env:
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PACKAGE_READ_TOKEN }}

      - name: Scan with SonarQube
        run: mvn -B sonar:sonar -Dsonar.pullrequest.key=${{ github.event.number }} -Dsonar.pullrequest.branch=${GITHUB_HEAD_REF} -Dsonar.pullrequest.base=${GITHUB_BASE_REF} -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PACKAGE_READ_TOKEN }}
